# Generated by Django 5.2.7 on 2025-10-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_equipment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='equipment_files/'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='equipment_images/'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
